# Generated by Django 2.1.7 on 2019-03-25 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20190325_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created',
            new_name='sent',
        ),
    ]
