# Generated by Django 2.1.7 on 2019-03-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20190324_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sent',
            field=models.DateField(auto_now_add=True),
        ),
    ]
