# Generated by Django 2.1.7 on 2019-03-25 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20190324_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='sent',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
