# Generated by Django 2.1.7 on 2019-03-25 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20190324_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='sent',
        ),
    ]
