# Generated by Django 2.1.7 on 2019-03-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=13)),
                ('vehicle_model', models.CharField(max_length=120)),
                ('vehicle_location', models.CharField(max_length=30)),
                ('message', models.TextField()),
            ],
        ),
    ]
